### PR TITLE
Execute code in a sandboxed environment

### PR DESCRIPTION
**Pull request by dialelo**
Still a long way to go but opening this early for getting feedback. The more eyes look at it the better. My approach has been to run the user-provided code in a thread pool that is sandboxed and doesn't allow them to access dangerous APIs (System.exit) or change the VM's settings. This is achieved with a inheritable thread local boolean flag that controls which threads are sandboxed ~~which i currently can break and have included a test for fixing~~.
- [x] Evaluate which [permissions](http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html) the sandbox must have
  - Currently no permissions are granted to the sandbox, we can build a safelist as we go.

~~\- [ ] Implement the sandbox [described in this paper](https://www.cs.cmu.edu/~clegoues/docs/coker15acsac.pdf)~~

References:
- [Permissions in the JDK](http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html)
- [Evaluating the flexibility of the Java Sandbox](https://www.cs.cmu.edu/~clegoues/docs/coker15acsac.pdf)
- [JDK 8 security enhancements](https://docs.oracle.com/javase/8/docs/technotes/guides/security/enhancements-8.html) 
- [Self-protecting sandbox using SecurityManager](https://tersesystems.com/2015/12/29/sandbox-experiment/)
- [A per-thread Java Security Manager](http://alphaloop.blogspot.com.es/2014/08/a-per-thread-java-security-manager.html)

### CODE REVIEW

**Comment by raulraja** [comment]
Amazing work, looking forward to have this enabled so we can finally bring some sanity to the evaluation process.

**Comment by raulraja** [comment]
@dialelo What is the status of this PR? Anything we can do to help push this forward? @franciscodr may be able to help here too if you need him to. Thanks!

**Comment by noelmarkham** [comment]
@raulraja I took a look at this, but TBH I was struggling to get much past what @dialelo had already done

**Comment by dialelo** [comment]
I've tried several approaches to sandboxing code, all of which have been unsuccessfull. I struggled because things don't work as documented, and the examples in the articles i consulted simply didn't work.

- Using a custom security manager: you can replace the JVM's security manager, and intercept every permission check to implement your own policy.
  + Tried sandboxing only certain threads and it worked, but the sandbox can easily be escaped by replacing the security manager from a privileged thread in, for instance, a global thread pool like `scala.concurrent....implicits.global`
  + Tried discerning if the permission check was for code loaded at runtime after compilation, but i couldn't distinguish between the stack frames of our code in the application and the code we load and code. Permissions across a stack seem to be computed as the intersection of all the permissions in the code that is in such stack. 
- Using a custom classloader 
  + Tried setting a custom protection domain, which in theory can have certain permissions attached, to load the code. Didn't work as documented. Even when using a custom domain with no permission i was able to do anything from the loaded code.
  + Tried combining a custom classloader + Policy approach, but both the stack frames of the loaded code and of the application end up having the custom classloader. This surprised me because the custom classloader used for compilation is not a descendant of the system classloader.

I've also tried using a custom Policy, and combinations of the approaches outlined above, with no success. By the end of this i was thinking whether it wouldn't be easier to move the code *execution* to a separate, non-privileged JVM, and comunicate with it through messaging.

**Comment by raulraja** [comment]
The concern with moving evaluation to it's own JVM it's bootstraping of dependencies + start + shutdown time and potentially a decrease of concurrent evaluations given the JVM will reserve RAM that may be never be used. If say there is 10 concurrent evaluations and each process takes 500m ram we can quickly exhaust the Heroku dyno allocated mem.

**Comment by raulraja** [comment]
@dialelo @noelmarkham can this be closed now?

**Comment by noelmarkham** [comment]
I think so. I'll leave the final decision up to @dialelo, considering the final solution was a workaround rather than "doing it properly," but I don't think I have any more energy to give this task :-)

**Comment by dialelo** [comment]
Let's close this for the moment and revisit in the future if we need to.

**Comment by dialelo** [comment]
I'll keep the branch around just in case.

**Pull request closed without merging**
